### ISSUE TITLE
html validator 4 stiehl

### ISSUE THREAD

**Issue by DanielMehlber** [DanielMehlber/super-duper-web-project#35]
Alle fertigen Seiten durch den Validator jagan

**Comment by Ph1L42** [comment]
Error: A script element with a defer attribute must not have a type attribute with the value module.
- Game Search Page
- du dummkopf

**Comment by Ph1L42** [comment]
Error: An img element must have an alt attribute, except under certain conditions. For details, consult [guidance on providing text alternatives for images]
- Game View Page
- Was kannst du eigentlich
